---
- hosts: localhost
  gather_facts: false
  vars:
    data: "Neeraj:APQPD0556F,Praveen:DSDPD0556F,Devendra:SNOPD0556B"
    _regex: "([a-zA-Z]*:)([A-Z]{5}[0-9]{4}[A-Z]{1}),([a-zA-Z]*:)([A-Z]{5}[0-9]{4}[A-Z]{1}),([a-zA-Z]*:)([A-Z]{5}[0-9]{4}[A-Z]{1})" #"^([a-zA-Z0-9_\-\.])+@([a-zA-Z0-9_\-\.]+)\.([a-zA-Z]{2,5})$"


  tasks:
    - name: Capture Data using regex
      debug:
        msg:
                - "{{ data | regex_replace(_regex, '\\1') }}"
                - "{{ data | regex_replace(_regex, '\\2') }}"
